local CONFIGS = {}

CONFIGS.wings = {
	STIFFNESS     = 150,
	DAMPING       = 3.2,
	INERTIA_SCALE = 0.02,

	SIDE_DEADZONE    = 2.0,
	FORWARD_DEADZONE = 0.7,

	FORWARD_DRAG_BIAS     = -0.01,
	FORWARD_YAW_REDUCTION = 0.80,
	FORWARD_MOTION_FULL   = 9,
	YAW_UNLOCK_ANGLE      = mathRad(7),
	YAW_FULL_UNLOCK       = mathRad(12),

	MOTION_TRAIL_SMOOTHING = 0.07,
	MOTION_ACCEL_INFLUENCE = 0.02,
	TRAIL_RELEASE          = 0.04,

	ROTATION_YAW_INFLUENCE   = 0.05,
	ROTATION_ROLL_INFLUENCE  = 0.55,
	ROTATION_PITCH_INFLUENCE = 0.08,
	ROTATION_SMOOTHING       = 0.22,

	ROLL_STIFFNESS = 50,
	ROLL_DAMPING   = 0.75,
	MAX_ROLL_ANGLE = mathRad(45),
	YAW_TO_ROLL    = 0.25,
	SIDE_TO_ROLL   = 0.02,

	WHIP_THRESHOLD = 3.0,
	WHIP_STRENGTH  = 1.5,
	WHIP_COOLDOWN  = 0.2,

	SMEAR_MAX_ANGLE  = mathRad(90),
	SMEAR_SPEED_FULL = 18,

	WAG_SPEED               = 0.7,
	WAG_AMPLITUDE           = 0.10,
	WAG_FADE_SPEED          = 0.05,
	WAG_SECONDARY_SPEED     = 4.5,
	WAG_SECONDARY_AMPLITUDE = 0.025,
	WAG_PITCH_BOB           = mathRad(1.2),
	WAG_ROLL_AMPLITUDE      = mathRad(2.5),
	WAG_ROLL_SPEED          = 3.8,

	ANIMATION_INFLUENCE        = 0.45,
	ANIMATION_LINEAR_INFLUENCE = 0.30,
	ANIMATION_MOTOR_INFLUENCE  = 0.22,
	ANIMATION_BLEND_SMOOTHING  = 0.25,

	YAW_TO_PITCH_COUPLING     = 0.05,
	PITCH_TO_YAW_COUPLING     = 0.015,
	YAW_VELOCITY_TO_PITCH     = 0.0015,
	PITCH_VELOCITY_TO_YAW     = 0.0008,

	CHAOS_STRENGTH = 0.012,
	CHAOS_RESPONSE = 0.08,
	CHAOS_DAMPING  = 0.90,

	SPRINT_SPEED           = 16,
	MIN_INVERSION_STRENGTH  = 0.12,
	MAX_INVERSION_STRENGTH  = 0.70,

	MAX_ANGLE = mathRad(60),
	TIMESTEP = 1 / 120,

	FLOOR_CHECK_DIST    = 2.0,
	FLOOR_MIN_PART_SIZE = 4,
	FLOOR_PUSH_STRENGTH = 100,
	FLOOR_CONTACT_DIST  = 0.35,

	RESTING_ROLL_BIAS = 0,
}

CONFIGS.tails = {
	STIFFNESS     = 50,
	DAMPING       = 2.2,
	INERTIA_SCALE = 0.045,

	SIDE_DEADZONE    = 0.8,
	FORWARD_DEADZONE = 0.75,

	FORWARD_DRAG_BIAS     = -0.008,
	FORWARD_YAW_REDUCTION = 0.40,
	FORWARD_MOTION_FULL   = 10,
	YAW_UNLOCK_ANGLE      = mathRad(12),
	YAW_FULL_UNLOCK       = mathRad(24),

	MOTION_TRAIL_SMOOTHING = 0.25,
	MOTION_ACCEL_INFLUENCE = 0.03,
	TRAIL_RELEASE          = 0.22,

	ROTATION_YAW_INFLUENCE   = 0.025,
	ROTATION_ROLL_INFLUENCE  = 0.38,
	ROTATION_PITCH_INFLUENCE = 0.04,
	ROTATION_SMOOTHING       = 0.35,

	ROLL_STIFFNESS = 25,
	ROLL_DAMPING   = 0.85,
	MAX_ROLL_ANGLE = mathRad(28),
	YAW_TO_ROLL    = 0.18,
	SIDE_TO_ROLL   = 0.012,

	WHIP_THRESHOLD = 4.0,
	WHIP_STRENGTH  = 0.9,
	WHIP_COOLDOWN  = 0.30,

	SMEAR_MAX_ANGLE  = mathRad(60),
	SMEAR_SPEED_FULL = 18,

	WAG_SPEED               = 3.5,
	WAG_AMPLITUDE           = 0.15,
	WAG_FADE_SPEED          = 0.20,
	WAG_SECONDARY_SPEED     = 3.0,
	WAG_SECONDARY_AMPLITUDE = 0.015,
	WAG_PITCH_BOB           = mathRad(0.1),
	WAG_ROLL_AMPLITUDE      = mathRad(2.0),
	WAG_ROLL_SPEED          = 3.0,

	ANIMATION_INFLUENCE        = 0.30,
	ANIMATION_LINEAR_INFLUENCE = 0.18,
	ANIMATION_MOTOR_INFLUENCE  = 0.22,
	ANIMATION_BLEND_SMOOTHING  = 0.35,

	YAW_TO_PITCH_COUPLING     = 0.015,
	PITCH_TO_YAW_COUPLING     = 0.012,
	YAW_VELOCITY_TO_PITCH     = 0.0010,
	PITCH_VELOCITY_TO_YAW     = 0.0008,

	CHAOS_STRENGTH = 0.004,
	CHAOS_RESPONSE = 0.04,
	CHAOS_DAMPING  = 0.96,

	SPRINT_SPEED           = 16,
	MIN_INVERSION_STRENGTH  = 0.12,
	MAX_INVERSION_STRENGTH  = 0.70,

	MAX_ANGLE = mathRad(60),
	TIMESTEP = 1 / 120,

	FLOOR_CHECK_DIST    = 2.0,
	FLOOR_MIN_PART_SIZE = 4,
	FLOOR_PUSH_STRENGTH = 90,
	FLOOR_CONTACT_DIST  = 0.35,

	RESTING_ROLL_BIAS = mathRad(18),
}
